services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongodb
    environment:
      - 'MONGO_INITDB_DATABASE=${MONGO_DB_NAME}'
      - 'MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}'
      - 'MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}'
    env_file:
      - .env
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

  zookeeper:
    image: 'confluentinc/cp-zookeeper:7.6.0'
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_LOG4J_ROOT_LOGLEVEL: "WARN"
    ports:
      - '2181:2181'
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "sh", "-c", "nc -z localhost 2181 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  kafka:
    image: 'confluentinc/cp-kafka:7.6.0'
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
      - '29092:29092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - kafka-data:/var/lib/kafka/data
    restart: on-failure
    command: >
      sh -c "chown -R 1000:1000 /var/lib/kafka || true &&
             /etc/confluent/docker/run"

  squadify-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: squadify-app
    depends_on:
      - mongodb
      - kafka
    ports:
      - '8080:8080'
    env_file:
      - .env
    environment:
      MONGO_HOST: mongodb
      KAFKA_BROKERS: kafka:9092
    restart: on-failure

volumes:
  mongo-data:
  zookeeper-data:
  kafka-data: